### PR TITLE
Create transcript_governance_implementation.md

### PR DESCRIPTION
**Pull request by eleventh19**
adding a reviewed transcript for the governance implementation panel

### CODE REVIEW

**Comment by ghettodev** [comment]
Seems like the dialogue gets progressively more incomprehensible as you get deeper into it. Would also be nice to have links to the video in the timestamps. 

Here's a link to the format we came up with at Maker that followed the same general flow: rev -> editor -> formating -> GH. 

I think for these to be useful in absence of watching them in tandem, the text will have to be lightly edited for clarity and intent as opposed to literal transcripts. Open to other opinions though. 

Moving the signoff process to hackmd before it gets to a PR will probably make this process less onerous as well.

**Comment by eleventh19** [comment]
Got it, thanks for the feedback. @jamesmcgirk offered to help clean it up and I sent him the HackMD files. once's that's updated, I'l nudge to review

**Comment by ghettodev** [comment]
Status update on this?

**Comment by eleventh19** [comment]
@ghettodev the draft in HackMD is updated and ready for your review

**Review by ghettodev — APPROVED** [review]
lgtm

**Comment by eleventh19** [comment]
Added the transcript to the post and the video

**Pull request merged**
