### PR TITLE
Update content_notable_works.md

### PR DESCRIPTION
**Pull request by 29988122**
List curated from Lucy Williams and Jerry Ho. TOC is also updated by VScode markdown editor.

https://www.smartcontractresearch.org/t/notable-works-in-cryptography/500/3

### CODE REVIEW

**Review by ghettodev — APPROVED** [review]
Amazing work @lw-scrf and @29988122

**Comment by ghettodev** [comment]
Add @lw-scrf and @29988122 as a contributor for doc and maintenance

**Comment by ghettodev** [comment]
Add @lw-scrf and as a contributor for doc

**Comment by ghettodev** [comment]
@all-contributors please add @lw-scrf and @29988122 for maintenance and doc.

**Comment by lw-scrf** [comment]
> Amazing work @lw-scrf and @29988122

Thanks!

**Pull request merged**
