### PR TITLE
Update grants_pan_african.md

### PR DESCRIPTION
**Pull request by vsterling**
Request to update the Pan African Microgrant doc with additional information and clarifying language.

### CODE REVIEW

**Review by ghettodev — CHANGES_REQUESTED** [review]
added one comment about links and tags

**Comment by twan-dev** [comment]
@Coinproz let's coordinate on this

**Comment by Coinproz** [comment]
> My question relates to the link to a list of papers available to be summaries. Since we're transitioning into a primary research program, that section will not be applicable going forward.
> 
> It was also established that we are not interested in "use case examinations", and primarily just "case studies".

I have no problem transitioning completely to primary, but I was under the impression that it was secondary for cases where case studies had been done, and primary in gaps and only done by qualified applicants?

I.e. some people are capable of doing secondary research but do not have enough experience to execute primary.  We can discuss on the call tomorrow to clarify

**Comment by vsterling** [comment]
Closing this and replacing it with a new PR. The markdown file contained violations to be fixed.

**Pull request closed without merging**
